services:
  compute-engine:
    build:
      context: ./compute_engine
    ports:
      - "7001:7001"

  api-gateway:
    build:
      context: ./api_gateway
    environment:
      COMPUTE_ENGINE_URL: http://compute-engine:7001
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - compute-engine
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orbital_catalog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
